# Generated by Django 5.0.4 on 2024-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoise',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
    ]
