# Generated by Django 5.0.4 on 2024-05-07 01:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaries',
            name='zenk_sal',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=15),
        ),
    ]
