# Generated by Django 5.0.4 on 2024-05-12 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invoise_aklasheh_sal_alter_invoise_paper_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiseSalaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('y_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('m_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('c_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('zahabi_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('faddi_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('sapgha_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('warnish_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('kohley_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('special_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('slofan_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('taksir_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('UV_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('film_sal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('zenk_sal', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=15)),
                ('invoise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoise')),
            ],
        ),
    ]
