# Generated by Django 5.0.4 on 2024-05-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoisesalaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoisesalaries',
            old_name='invoise',
            new_name='invoise_name',
        ),
    ]
