# Generated by Django 5.0.4 on 2024-05-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_invoise_invoisesalaries_invoise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoisesalaries',
            old_name='invoise_name',
            new_name='invoise',
        ),
    ]
