# Generated by Django 5.0.6 on 2024-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_invoise_name_invoisesalaries_invoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoisesalaries',
            name='invoise',
            field=models.CharField(max_length=50),
        ),
    ]
