# Generated by Django 5.0.6 on 2024-05-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_invoisesalaries_invoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoisesalaries',
            name='invoise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoise'),
        ),
    ]
