# Generated by Django 5.0.6 on 2024-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoisesalaries_invoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoisesalaries',
            name='invoise',
            field=models.CharField(max_length=50),
        ),
    ]
